version: "3"

services:
  webserver_wordpress:
    build:
      context: ./bin/${PHPVERSION}
    container_name: webserver_wordpress
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
        #    links: 
        #      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
#      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${PHP_INI-./config/php/php.ini}:/etc/php5/apache2/php.ini
      - ${PHP_INI-./config/php/php.ini}:/etc/php5/cli/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
#      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ./config/ssl/2020/:/etc/ssl/certs/2020
    networks:
      - wordpress-network

  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'database'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        #- ./mysql/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --innodb-use-native-aio=0 --skip-name-resolve  
    networks:
      - wordpress-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '8081:80'
    networks:
      - wordpress-network 

  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    networks:
      - wordpress-network
  
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '9101:9101'

networks:
  wordpress-network:
    driver: bridge
